name: OIDC role connection check

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  check-oidc-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::883429660395:role/GithubActionsS3Role
          aws-region: us-east-1

      - name: Verify caller identity
        run: |
          aws sts get-caller-identity

